# Only runs frontend
version: '3'
services:
  frontend:
    build:
      context: frontend-shared
      dockerfile: Dockerfile.dev
    command: "npm run watch:validation"
    environment:
      # Public URL is settable from the
      # local environment
      - DEBUG=1
      # The two possible app modes are ANNOTATION and PREDICTION
      - APPMODE=PREDICTION
      - PUBLIC_URL=/
      - API_BASE_URL=http://cosmos3.chtc.wisc.edu:8081/search
    volumes:
      - ./frontend-shared/src:/user/src
      - ./frontend-shared/bundled-deps/ui-components:/user/bundled-deps/ui-components
      - node_modules:/user/node_modules
      - visualizer_dist:/user/dist
      - webpack_cache:/user/.cache
  gateway:
    image: nginx
    ports:
      - "${VALIDATION_PORT:-5080}:80"
    volumes:
      - visualizer_dist:/frontend:ro
      - ./frontend-shared/nginx.frontend-only.conf:/etc/nginx/nginx.conf:ro
volumes:
  visualizer_dist:
  webpack_cache:
  node_modules:
#
# # can now do things like connections.create_connection(hosts=['es01'], timeout=20)
# networks:
#    default:
#       external:
#          name: elasticsearch_esnet
