# Only runs frontend
version: '3'
services:
  frontend:
    build:
      context: frontend-shared
      dockerfile: Dockerfile.build
    environment:
      # Public URL is settable from the
      # local environment
      - ENVIRONMENT=production
      - MODE=${MODE:-visualizer}
      # The two possible app modes are ANNOTATION and PREDICTION
      - APPMODE=PREDICTION
      - PUBLIC_URL=/
      - API_BASE_URL=http://cosmos3.chtc.wisc.edu:8081/search
    ports:
      - "${APP_PORT:-5080}:80"
#
# # can now do things like connections.create_connection(hosts=['es01'], timeout=20)
# networks:
#    default:
#       external:
#          name: elasticsearch_esnet
