version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "5080:80"
    environment:
      # Public URL is settable from the
      # local environment
      - DEBUG=1
      - APPMODE=PREDICTION
    volumes:
      - ./frontend:/user
      - /user/node_modules
      - /user/ui-components/node_modules
      - /user/.cache
      - ./logs:/logs

# can now do things like connections.create_connection(hosts=['es01'], timeout=20)
networks:
   default:
      external:
         name: elasticsearch_esnet
