# Only runs frontend
version: '3'
services:
  frontend_dist:
    build:
      context: frontend-shared
      dockerfile: Dockerfile.build
      args:
        MODE: ${MODE:-visualizer}
        ENVIRONMENT: production
        PUBLIC_URL: ${PUBLIC_URL:-/}
        API_BASE_URL: ${API_BASE_URL:-/search}
        WORD2VEC_API_BASE_URL: ${WORD2VEC_API_BASE_URL:-/word2vec}
    environment:
      # Public URL is settable from the
      # local environment
      - ENVIRONMENT=production
      - MODE=${MODE:-visualizer}
      - PUBLIC_URL=/
      - API_BASE_URL=/search
      - WORD2VEC_API_BASE_URL=/word2vec
    ports:
      - "${APP_PORT:-5080}:80"
