version: '3'
services:
    gateway:
      image: uwcosmos/cosmos_viz_gateway
      ports:
        - "5002:80"
      depends_on:
        - image-tagger-api
      volumes:
        - ./_data/logs:/logs
        - ${PIPELINE_OUTPUT}/images:/images:ro

    image-tagger-api:
      image: uwcosmos/cosmos_viz_api
      depends_on:
        - db

    db:
      image: uwcosmos/cosmos_viz_db
      environment:
        - POSTGRES_DB=annotations
      ports:
        - "54321:5432"
      expose:
        - 5432

    kb_visualizer:
      image: uwcosmos/cosmos_viz_kbviz
      ports:
        - "8051:8051"
      expose:
        - 8051
      environment:
        - PG_CONN_STR=postgresql://postgres:@db:5432/annotations 
        - PG_EQUATION_SCHEMA=equations
      volumes:
        - ./_data/kb_output:/app/output
        - ./_data/kb_output/img/:/app/img
      command: $PG_CONN_STR python server.py

    import_data:
      image: uwcosmos/cosmos_viz_import_data
      depends_on:
        - db
      environment:
        - PG_CONN_STR=postgresql://postgres:@db:5432/annotations
      volumes:
        - ${PIPELINE_OUTPUT}:/output
        - ${PIPELINE_OUTPUT}/images:/images:rw
 
