version: '3'
services:
  image-tagger-api:
    build: api
    environment:
      # This should be changeable obviously
      - IMAGE_TAGGER_API_MODE=annotate
    ports:
      - 5454:5454
    depends_on:
      - db
    volumes:
      - ./_data/images:/images/test
  db:
    image: postgres:11.1-alpine
    volumes:
      - ./setup:/docker-entrypoint-initdb.d/
      - ./_data/pg-cluster:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=annotations
    ports:
      - "54321:5432"
    expose:
      - 5432

