# Only runs frontend
version: '3'
services:
  frontend:
    build: visualizer-app
    environment:
      # Public URL is settable from the
      # local environment
      - DEBUG=1
      # The two possible app modes are ANNOTATION and PREDICTION
      - APPMODE=PREDICTION
      - PUBLIC_URL=/
      - API_BASE_URL=http://cosmos1.chtc.wisc.edu:5080/search
      - IMAGE_BASE_URL=http://cosmos1.chtc.wisc.edu:5080/images/
    volumes:
      - ./frontend-shared:/user/shared
      - visualizer_dist:/user/dist
  gateway:
    image: nginx
    ports:
      - "5080:80"
    volumes:
      - visualizer_dist:/frontend:ro
      - ./visualizer-app/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  visualizer_dist:
#
# # can now do things like connections.create_connection(hosts=['es01'], timeout=20)
# networks:
#    default:
#       external:
#          name: elasticsearch_esnet
