name: Build master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build and push Docker images (Visualizer app)
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: ./apps/visualizer-xdd/Dockerfile
          build_args: PUBLIC_URL=/set_visualizer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uwxdd/cosmos_set_visualizer
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
      - name: Build and push Docker images (Tagger app)
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: ./apps/tagger-xdd/Dockerfile
          build_args: PUBLIC_URL=/set_visualizer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uwxdd/cosmos_set_tagger
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
