name: Build + push image from PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker images (Visualizer app)
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: ./apps/visualizer-xdd/Dockerfile
          cache_from: uwxdd/cosmos_set_visualizer
          build_args: PUBLIC_URL=/set_visualizer,XDD_BASE_URL=https://xdddev.chtc.io,XDD_API_KEY=${{ secrets.XDD_API_KEY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uwxdd/cosmos_set_visualizer
          tags: staging-pr${{ github.event.number }}-${{ steps.vars.outputs.sha_short }}

      - name: Build and push Docker images (Tagger app)
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: ./apps/tagger-xdd/Dockerfile
          cache_from: uwxdd/cosmos_set_visualizer
          build_args: PUBLIC_URL=/tagger,XDD_BASE_URL=https://xdddev.chtc.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uwxdd/cosmos_set_tagger
          tags: staging-pr${{ github.event.number }}-${{ steps.vars.outputs.sha_short }}
