name: Build image from PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./frontend-shared
          file: ./frontend-shared/Dockerfile.xdd
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: uwxdd/cosmos_set_visualizer
          tags: staging-pr${{ github.event.number }}-${{ steps.vars.outputs.sha_short }} 
